services:
  db:
    image: postgres:15
    container_name: mattermost_db
    restart: always
    environment:
      POSTGRES_DB: mattermost
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mattermost-network
  mattermost:
    image: mattermost/mattermost-team-edition:latest
    container_name: mattermost_app
    restart: always
    environment:
      MM_SQLSETTINGS_DRIVERNAME: "postgres"
      MM_SQLSETTINGS_DATASOURCE: "postgres://admin:admin@123@db:5432/mattermost?sslmode=disable"
    volumes:
      - mattermost_data:/mattermost/data
    networks:
      - mattermost-network
        #   ports:
      #    - "1165:8065"

        #  depends_on:
      #     - db
  nginx:
    image: nginx:latest
    container_name: mattermost_nginx
    restart: always
    volumes:
       - ./nginx.conf:/etc/nginx/conf.d/default.conf
       - ./ssl:/media/mattermost/ssl
    ports:
      - "1120:443"
    networks:
      - mattermost-network

volumes:
   postgres_data:
   mattermost_data:

networks:
   mattermost-network:

